### ISSUE TITLE
Error reading or parsing /data/configuration.yaml / dashboard.yaml

### ISSUE THREAD

**Issue by Holewijn** [matt8707/addon-ha-fusion#1]
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
Listening on 0.0.0.0:5050
Error reading or parsing ./data/configuration.yaml: Error: ENOENT: no such file or directory, open './data/configuration.yaml'
    at async open (node:internal/fs/promises:633:25)
    at async readFile (node:internal/fs/promises:1242:14)
    at async loadFile (file:///rootfs/build/server/chunks/3-xnNkqMtk.js:8:18)
    at async Promise.all (index 0)
    at async load (file:///rootfs/build/server/chunks/3-xnNkqMtk.js:16:38)
    at async load_server_data (file:///rootfs/build/server/index.js:1891:18)
    at async file:///rootfs/build/server/index.js:3301:18 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './data/configuration.yaml'
}
Error reading or parsing ./data/dashboard.yaml: Error: ENOENT: no such file or directory, open './data/dashboard.yaml'
    at async open (node:internal/fs/promises:633:25)
    at async readFile (node:internal/fs/promises:1242:14)
    at async loadFile (file:///rootfs/build/server/chunks/3-xnNkqMtk.js:8:18)
    at async Promise.all (index 1)
    at async load (file:///rootfs/build/server/chunks/3-xnNkqMtk.js:16:38)
    at async load_server_data (file:///rootfs/build/server/index.js:1891:18)
    at async file:///rootfs/build/server/index.js:3301:18 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './data/dashboard.yaml'
}
```

**Comment by yaggermr** [comment]
Unraid Docker similar issue
Error reading or parsing ./data/configuration.yaml: [Error: ENOENT: no such file or directory, open './data/configuration.yaml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './data/configuration.yaml'
}

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/releases/tag/2023.12.4
